apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-secrets
  namespace: todo
spec:
  encryptedData:
    MONGO_PASSWORD: AgAI43/62VZiRN4erUUMz4z9UJrD00nxwjD7ijyTVY6/U7/E1vGOb4zd+YxeWGHqf0cve+CFVulKrHK3ya9iGEmcSRFUdTFsPHRH6+S0gqfaOALmdmNIBvMpy67nXDmqrZWmIsPEzAXCtWBRjaHdwC8rzy0jF0aOM4hOyfueSSwYJk+7r7IfOk04su9lrykZp17R2D/dSer7vhEcKu9DQlikSbwB6bV9yr/l590VvPYdOYUiyHQiqfKYqrwi39hp1ekS2BbyshoQi8R3ZwjTUovEFD9BSm7Hjek+hxGxeJdNs82Epeg7ykHhTWo8Cf7KR0sHCw93oB/x1a7mho75JNFs3XkOG4sF+4y4DaL86K1CczNtnPoSauTUeClzfpkqUmIClBmxGZSb0rUf7xQouXapEUTV6f6da/7wJVhBVAnwmLS7jV+8K0hb+NhPo9qdlGdN8P1J/rHq5tP/iDZnTd/fyKrHi8/9sjLS7JPlCB5GnQskBK1qMzhHH96oCDPoDvNJwT0AY8NGTNh16hNGzs0BRcz5TOH53ug2fBtd3aTAb9FjUqJrprxSAE0yYKgXXjaSSdgWdBRw54hLuuogAwoeY4jHx8DTbK4N7wjrA1Qqak9FhHaulPrce6I+rg5/pq3c80eaXmBxT6rkRRxmSx6Yq4o42YQWXtCNBEFnL76NQt4Ka1wHnWnqD7+68SHtC6QO45uPGOY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: todo-secrets
      namespace: todo

