apiVersion: v1
kind: Service
metadata:
  namespace: todo
  name: todo-frontend-svc
spec:
  type: LoadBalancer
  selector:
    app: todo-frontend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
