apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pingpong-secrets
  namespace: exercises
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBRjrqBt6qDy+qUb8eyZA+Zfvelq2TNhFiOq1AkXN2LvKnS0BWC3AUKLdBa6P+NLT0DvFYl2G/s1YIouegriOScLH+miXpSZaf2gE6/p5s9vDuu1+QYITrLL0MxvwfJTowJrqShbjip0dvtJMmkQr4szCfL5gauCeKiCNfWcZ8Vud4iMvT5EEqm+5DZrOcmgbxz/5XGNbcoFux+zJJhnLXxQ7CLERPZ3hyMNAd2pTWGRjkTprzV/1vary2vuJMqJwpxsrT/kH5XVoSZlJhBgg9PA28p4ct6kBVaDBHzoysr4OhMJNhpawgcHTBEOYtEO1qhQF/V5sVfphDe4g8ps9/FYPntm8IFtDvMEAAFBKIE5gSrAfNeDQCBXpaEFlyya2KSoifNLxak1jBdCKlALHs9jkHO9s8+ioXb1m4WsD2hyI74O5oOg4Mg5ZmHZ/NF5Z4Iw9to0EO4R823FJHr6unPBPs/axpXj7vgYMd25yH6stoval4mdwUQ8jtHJAIARVmSUiHN8iq46iWO82BgZPHc+XXQgoF5HCEGT1Zv333DY9fhTYH5ZMjaklo3Na8HnUGYO2zSO0zzMZz7dhbn6sYEW9XA8sclHop+s5TzTmx8dyzWQgteg6d4arFN42uoYYP/NT3s+rkVI3kLa2fTXuWq/1i4GZvnXMmG99THIr/D2tudSMl588gPhRndifIhlthG662ldNQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: pingpong-secrets
      namespace: exercises

