apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: pingpong-svc
spec:
  type: LoadBalancer
  selector:
    app: pingpong
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
