apiVersion: v1
kind: Service
metadata:
  namespace: todo
  name: todo-backend-svc
spec:
  type: NodePort
  selector:
    app: todo-backend
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
