apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-secrets
  namespace: todo
spec:
  encryptedData:
    MONGO_PASSWORD: AgCssKrPt7Wb2i0OXoeshIdHfEmHRV8dglcWFMYwb5BECqKFRPBl9eQLnZx8cxmBopD9250lB9Quxfknd9BVRtFXk5bgF2Wzskzxb8w7Ymp17om5wSqIYCg88Qwh5yU6faT0q3v9RhXlJFbf/gjbzbw8NoAFdEzTvLHjTB4g2dL1NpE0bSQL2X60ce1nSCvSBKDs+XAcZFa+kq4lQT5bFNF5hkJV4NnQCJGpEcOKZcLF4BZ8tkJKR9RHshxRwpezZNvfAk9Aw9fVjM4Jka9JMycYTJCwqTZvsqAl47aLLD3hkHFizlKZFRu+oOhkmseuNXHEFvyQnW2cLuU5+Ndyg6LgVBr3vv6rb7PKef6M4i4Kr+hi+7PhDvcMmKj2DHeBF0OKam/tCUvTt1F9wYl2QuoAyJ4fqgI1/USjlGUyyvj6ocW+WZcVhJ0pkyhv9mmXF8KrBIHZWKhpGhtZfOT0Eo3U+CtPQu59U7PQlrIE1Uj0xfD0JAmAW1migW0LgtmUEeZidh3+76rApD2Z3dkyNwCd0xuHN0j2T9u2zvS2jqYvXagyGcDVgECTpBb7kOEnvMLa+vPuZLXL0mxGSJI4SWZhqNHLf1RW3h2YMMYYIGCR9OZWugECvQhrWvnnw3TDAdpLc1x0hRb1vSkEYpfkJXA2G1Gjtm9yXSIWmmRmuJ5l3lFNlUjKCwbC5JS8Uwj/u6LIoVanUTk=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: todo-secrets
      namespace: todo

